version: 2

sources:
  - name: test
    database: airbnb
    schema: raw
    freshness:
      error_after:
        count: 2
        period: minute
      warn_after:
        count: 1
        period: minute
    tables:
      - name: raw_hosts
      - name: raw_listings
      - name: raw_reviews
      - name: ads
      - name: c
      - name: emp
      - name: dept
      - name: raw_orders
      - name: raw_Bankorders
      - name: raw_payments
      - name: raw_customers

  - name: Exp
    database: MYDB
    schema: public
    tables:
      - name: Transactions
        columns:
          - name: Transaction_date
          - name: Prod_id
          - name: user_id
